# Generated by Django 5.0.6 on 2024-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(blank=True, default=4, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Просмотр баланса',
                'verbose_name_plural': 'Просмотр баланса',
            },
        ),
    ]
